"use client";

import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import JsBarcode from "jsbarcode";

type Asset = { id:number; assetCode:string; name:string; category:string; status:"available"|"pulled_out"; currentEvent:string|null; updatedAt:string };
type Movement = { id:number; assetCode:string; assetName:string; action:"pullout"|"return"; eventName:string; operatorName:string; createdAt:string };
type InventoryData = { items:Asset[]; movements:Movement[]; summary:{ total:number; available:number; pulledOut:number; returnedToday:number } };
type Staff = { id:number; employeeId:string; fullName:string; position:string; role:string; contactNumber:string; username:string; accountStatus:string; attendanceStatus:string; twoFactorEnabled:number };
type Client = { id:number; clientCode:string; name:string; company:string; contact:string; email:string; balance:number };
type EventRow = { id:number; eventCode:string; title:string; clientName:string; venue:string; eventDate:string; status:string; crewCount:number; equipmentCount:number };
type Quote = { id:number; quoteNo:string; clientName:string; eventName:string; amount:number; status:string; createdAt:string };
type FinanceRow = { id:number; type:string; category:string; description:string; amount:number; eventName:string; entryDate:string };
type StockRow = { id:number; itemCode:string; name:string; category:string; stock:number; minStock:number; unit:string; supplier:string };
type AlertRow = { id:number; type:string; title:string; message:string; severity:string; isRead:number; dueDate:string; createdAt:string };
type MaintenanceRow = { id:number; assetCode:string; issue:string; status:string; dueDate:string; technician:string };
type BackOfficeData = { staff:Staff[]; clients:Client[]; events:EventRow[]; quotations:Quote[]; finance:FinanceRow[]; warehouse:StockRow[]; notifications:AlertRow[]; maintenance:MaintenanceRow[]; metrics:{ attendancePresent:number; attendanceTotal:number; monthlyRevenue:number; monthlyExpenses:number } };
type View = "dashboard"|"equipment"|"pullout"|"events"|"clients"|"staff"|"finance"|"warehouse"|"reports"|"notifications"|"security";
type ModalKind = "client"|"event"|"staff"|"quotation"|"finance"|"stock"|"staff-edit";
type AuthUser = { id:number;employeeId:string;fullName:string;position:string;role:string;username:string };

const peso = new Intl.NumberFormat("en-PH", { style:"currency", currency:"PHP", maximumFractionDigits:0 });
const nav: Array<{id:View;label:string;icon:string;group:string}> = [
  {id:"dashboard",label:"Dashboard",icon:"grid",group:"OPERATIONS"},{id:"equipment",label:"Equipment Inventory",icon:"box",group:"OPERATIONS"},
  {id:"pullout",label:"Pull-Out & Return",icon:"scan",group:"OPERATIONS"},{id:"events",label:"Events & Calendar",icon:"calendar",group:"OPERATIONS"},
  {id:"clients",label:"Clients & Quotations",icon:"users",group:"BUSINESS"},{id:"staff",label:"Staff & Attendance",icon:"badge",group:"BUSINESS"},
  {id:"finance",label:"Finance",icon:"wallet",group:"BUSINESS"},{id:"warehouse",label:"Warehouse",icon:"warehouse",group:"BUSINESS"},
  {id:"reports",label:"Reports",icon:"report",group:"CONTROL"},{id:"notifications",label:"Notifications",icon:"bell",group:"CONTROL"},
  {id:"security",label:"Security Center",icon:"shield",group:"CONTROL"},
];

function Icon({ name, size=19 }: {name:string;size?:number}) {
  const p:Record<string,React.ReactNode> = {
    grid:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
    box:<><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9L12 3Z"/><path d="m4.5 7.7 7.5 4.2 7.5-4.2M12 21v-9"/></>,
    scan:<><path d="M4 7V5a1 1 0 0 1 1-1h2M17 4h2a1 1 0 0 1 1 1v2M20 17v2a1 1 0 0 1-1 1h-2M7 20H5a1 1 0 0 1-1-1v-2"/><path d="M7 12h10M8 9v6M11 9v6M14 9v6M17 9v6"/></>,
    calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>,
    users:<><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.8M16 3.2a4 4 0 0 1 0 7.6"/></>,
    badge:<><circle cx="12" cy="8" r="5"/><path d="M8.5 12 7 22l5-3 5 3-1.5-10"/></>,
    wallet:<><rect x="3" y="5" width="18" height="15" rx="2"/><path d="M16 12h5M3 9h14"/></>,
    warehouse:<><path d="m3 10 9-7 9 7v11H3z"/><path d="M7 14h10M7 18h10"/></>,
    report:<><path d="M6 2h9l4 4v16H6z"/><path d="M14 2v5h5M9 13h6M9 17h6M9 9h2"/></>,
    bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>,
    shield:<><path d="M12 22s8-3 8-10V5l-8-3-8 3v7c0 7 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></>,
    search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
    plus:<path d="M12 5v14M5 12h14"/>,menu:<path d="M4 6h16M4 12h16M4 18h16"/>,close:<path d="m6 6 12 12M18 6 6 18"/>,
    out:<><path d="M9 11 4 6l5-5M4 6h11a5 5 0 0 1 5 5v2"/><path d="M5 14v5a2 2 0 0 0 2 2h9"/></>,
    back:<><path d="m15 11 5-5-5-5M20 6H9a5 5 0 0 0-5 5v2"/><path d="M19 14v5a2 2 0 0 1-2 2H8"/></>,
    print:<><path d="M6 9V3h12v6M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><path d="M6 14h12v7H6z"/></>,
    download:<><path d="M12 3v12M7 10l5 5 5-5"/><path d="M4 21h16"/></>,eye:<><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></>,
    trash:<><path d="M3 6h18M8 6V4h8v2M19 6l-1 15H6L5 6M10 11v6M14 11v6"/></>,
  };
  return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{p[name] ?? <circle cx="12" cy="12" r="8"/>}</svg>;
}

function Status({ value }: {value:string}) { return <span className={`pill ${value.toLowerCase().replaceAll(" ","-")}`}>{value.replaceAll("_"," ")}</span>; }
function Avatar({ name }: {name:string}) { return <span className="avatar">{name.split(" ").slice(0,2).map(x=>x[0]).join("")}</span>; }
function Barcode({ value }: {value:string}) { const ref=useRef<SVGSVGElement>(null); useEffect(()=>{ if(ref.current) JsBarcode(ref.current,value,{format:"CODE128",height:42,width:1.45,margin:4,displayValue:true,fontSize:11}); },[value]); return <svg ref={ref} aria-label={`Barcode ${value}`}/>; }

function Scanner({ onCode,onClose }: {onCode:(code:string)=>void;onClose:()=>void}) {
  const videoRef=useRef<HTMLVideoElement>(null); const streamRef=useRef<MediaStream|null>(null); const frameRef=useRef<number|null>(null); const [manual,setManual]=useState(""); const [error,setError]=useState("");
  useEffect(()=>{ let active=true; (async()=>{ try { if(!("BarcodeDetector" in window)) throw new Error("Camera auto-scan is not supported by this browser."); const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false}); streamRef.current=stream; if(!videoRef.current||!active)return; videoRef.current.srcObject=stream; await videoRef.current.play(); const D=(window as unknown as {BarcodeDetector:new(o:{formats:string[]})=>{detect:(v:HTMLVideoElement)=>Promise<Array<{rawValue:string}>>}}).BarcodeDetector; const detector=new D({formats:["code_128","code_39","qr_code"]}); const tick=async()=>{if(!active||!videoRef.current)return;try{const r=await detector.detect(videoRef.current);if(r[0]?.rawValue){onCode(r[0].rawValue);return;}}catch{} frameRef.current=requestAnimationFrame(tick)}; tick(); } catch(e){setError(e instanceof Error?e.message:"Camera unavailable.");} })(); return()=>{active=false;if(frameRef.current)cancelAnimationFrame(frameRef.current);streamRef.current?.getTracks().forEach(t=>t.stop());}; },[onCode]);
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Barcode scanner"><div className="scanner-card"><div className="modal-head"><div><span className="kicker">BARCODE / QR SCANNER</span><h2>Scan equipment label</h2></div><button className="icon-btn" onClick={onClose} aria-label="Close"><Icon name="close"/></button></div><div className="camera-frame"><video ref={videoRef} muted playsInline/><div className="scan-line"/><div className="scan-corners"/></div>{error&&<p className="camera-error">{error} Use manual code below.</p>}<form className="manual-row" onSubmit={e=>{e.preventDefault();if(manual.trim())onCode(manual.trim().toUpperCase())}}><input aria-label="Manual barcode" value={manual} onChange={e=>setManual(e.target.value)} placeholder="e.g. SA-SPK-001"/><button className="btn primary">Process</button></form></div></div>;
}

function BackOfficeModal({kind,data,staff,onClose,onSubmit,submitting}:{kind:ModalKind;data:BackOfficeData;staff:Staff|null;onClose:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>,kind:ModalKind)=>void;submitting:boolean}) {
  const title={client:"Add New Client",event:"Create New Event",staff:"Add Staff Account",quotation:"Create Quotation",finance:"Record Transaction",stock:"Adjust Warehouse Stock","staff-edit":"Update Staff Status"}[kind];
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label={title}><form className="form-card form-wide" onSubmit={e=>onSubmit(e,kind)}><div className="modal-head"><div><span className="kicker">CLOUD DATABASE</span><h2>{title}</h2></div><button type="button" className="icon-btn" onClick={onClose} aria-label="Close"><Icon name="close"/></button></div>
    {kind==="client"&&<div className="form-grid"><label>Client Code<input name="clientCode" required placeholder="CL-005"/></label><label>Client / Contact Name<input name="name" required placeholder="Juan Dela Cruz"/></label><label>Company<input name="company" placeholder="Company or family name"/></label><label>Contact Number<input name="contact" required inputMode="tel" placeholder="0917 000 0000"/></label><label>Email<input name="email" type="email" placeholder="client@example.com"/></label><label>Opening Balance<input name="balance" type="number" min="0" defaultValue="0"/></label></div>}
    {kind==="event"&&<div className="form-grid"><label>Event Code<input name="eventCode" required placeholder="EV-2607-05"/></label><label>Event Title<input name="title" required placeholder="Corporate Launch"/></label><label>Client<select name="clientName" required defaultValue=""><option value="">Select client</option>{data.clients.map(c=><option key={c.id} value={c.name}>{c.name} — {c.company}</option>)}</select></label><label>Venue<input name="venue" required placeholder="Event venue"/></label><label>Event Date<input name="eventDate" type="date" required/></label><label>Status<select name="status" defaultValue="confirmed"><option value="quotation">Quotation</option><option value="confirmed">Confirmed</option><option value="preparation">Preparation</option><option value="completed">Completed</option></select></label><label>Crew Count<input name="crewCount" type="number" min="0" defaultValue="0"/></label><label>Equipment Count<input name="equipmentCount" type="number" min="0" defaultValue="0"/></label></div>}
    {kind==="staff"&&<div className="form-grid"><label>Employee ID<input name="employeeId" required placeholder="SA-EMP-007"/></label><label>Full Name<input name="fullName" required placeholder="Full name"/></label><label>Position<input name="position" required placeholder="Job position"/></label><label>Role<select name="role" required defaultValue="Crew"><option>Super Admin</option><option>Admin</option><option>Office Staff</option><option>Warehouse Staff</option><option>Technician</option><option>Crew</option></select></label><label>Contact Number<input name="contactNumber" required inputMode="tel"/></label><label>Username<input name="username" required autoComplete="off"/></label><label className="span-2">Temporary Password<input name="temporaryPassword" required type="password" minLength={10} autoComplete="new-password" placeholder="At least 10 characters"/></label><label>Attendance<select name="attendanceStatus" defaultValue="present"><option value="present">Present</option><option value="on-site">On-site</option><option value="absent">Absent</option><option value="leave">On leave</option></select></label><label className="check-label"><input name="twoFactorEnabled" type="checkbox"/> 2FA enrolled</label></div>}
    {kind==="quotation"&&<div className="form-grid"><label>Quotation Number<input name="quoteNo" required placeholder="QT-2026-074"/></label><label>Client<select name="clientName" required defaultValue=""><option value="">Select client</option>{data.clients.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></label><label>Event / Project<input name="eventName" required placeholder="Event title"/></label><label>Amount<input name="amount" required type="number" min="1"/></label><label>Status<select name="status" defaultValue="pending"><option value="pending">Pending</option><option value="sent">Sent</option><option value="approved">Approved</option><option value="declined">Declined</option></select></label></div>}
    {kind==="finance"&&<div className="form-grid"><label>Transaction Type<select name="type" defaultValue="income"><option value="income">Income</option><option value="expense">Expense</option></select></label><label>Category<input name="category" required placeholder="Event Payment"/></label><label className="span-2">Description<input name="description" required placeholder="Transaction description"/></label><label>Amount<input name="amount" required type="number" min="1"/></label><label>Date<input name="entryDate" required type="date" defaultValue={new Date().toISOString().slice(0,10)}/></label><label className="span-2">Event<select name="eventName" defaultValue=""><option value="">Not event-related</option>{data.events.map(e=><option key={e.id} value={e.title}>{e.title}</option>)}</select></label></div>}
    {kind==="stock"&&<div className="form-grid"><label className="span-2">Warehouse Item<select name="itemCode" required defaultValue=""><option value="">Select item</option>{data.warehouse.map(w=><option key={w.id} value={w.itemCode}>{w.itemCode} — {w.name} ({w.stock} {w.unit})</option>)}</select></label><label>Adjustment<input name="delta" required type="number" placeholder="Use - for stock out"/></label><label>Reason<input name="reason" required placeholder="Received / Used / Correction"/></label></div>}
    {kind==="staff-edit"&&staff&&<div className="form-grid"><input type="hidden" name="id" value={staff.id}/><div className="form-readonly span-2"><Avatar name={staff.fullName}/><div><b>{staff.fullName}</b><small>{staff.employeeId} • {staff.role}</small></div></div><label>Attendance<select name="attendanceStatus" defaultValue={staff.attendanceStatus}><option value="present">Present</option><option value="on-site">On-site</option><option value="absent">Absent</option><option value="leave">On leave</option></select></label><label>Account Status<select name="accountStatus" defaultValue={staff.accountStatus}><option value="active">Active</option><option value="inactive">Inactive</option><option value="suspended">Suspended</option></select></label>{staff.role==="Super Admin"&&staff.username==="stefan"?<label className="span-2">Reset 6-Digit Admin PIN (optional)<input name="temporaryPassword" type="password" inputMode="numeric" pattern="[0-9]{6}" minLength={6} maxLength={6} autoComplete="new-password" placeholder="Leave blank to keep current PIN"/></label>:<label className="span-2">Reset Password (optional)<input name="temporaryPassword" type="password" minLength={10} autoComplete="new-password" placeholder="Leave blank to keep current password"/></label>}<label className="check-label span-2"><input name="twoFactorEnabled" type="checkbox" defaultChecked={Boolean(staff.twoFactorEnabled)}/> 2FA enrolled</label></div>}
    <div className="form-actions"><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary" disabled={submitting}>{submitting?"Saving…":"Save to Cloud"}</button></div>
  </form></div>;
}

function AuthScreen({setupRequired,onAuth}:{setupRequired:boolean;onAuth:(user:AuthUser)=>void}){
  const [mode,setMode]=useState<"login"|"setup">(setupRequired?"setup":"login");
  const [loginType,setLoginType]=useState<"admin"|"staff">(setupRequired?"staff":"admin");
  const [busy,setBusy]=useState(false),[error,setError]=useState("");
  async function authRequest(payload:Record<string,unknown>){
    for(let attempt=0;attempt<2;attempt++){
      const r=await fetch(`/api/auth?attempt=${Date.now()}`,{method:"POST",credentials:"include",cache:"no-store",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify(payload)});
      const raw=await r.text(),contentType=r.headers.get("content-type")??"";
      if(contentType.includes("application/json")){const body=JSON.parse(raw);if(!r.ok)throw new Error(body.error||"Unable to sign in.");return body}
      if(attempt===0){await new Promise(resolve=>window.setTimeout(resolve,450));continue}
      throw new Error("Login service did not respond correctly. Please tap Login again.");
    }
    throw new Error("Unable to reach the login service.");
  }
  async function submit(e:FormEvent<HTMLFormElement>){
    e.preventDefault();setBusy(true);setError("");
    const values=Object.fromEntries(new FormData(e.currentTarget));
    try{const body=await authRequest({action:mode,...values});onAuth(body.user)}
    catch(err){setError(err instanceof Error?err.message:"Unable to sign in.")}finally{setBusy(false)}
  }
  const adminAccess=mode==="setup"||loginType==="admin";
  return <main className="auth-shell"><section className="auth-brand"><img className="auth-logo" src="/stageability-logo.jpg" alt="Stageability Lights and Sounds logo"/><span>STAGEABILITY LIGHTS &amp; SOUNDS</span><h1>Equipment Operations Portal</h1><p>Secure pull-out, warehouse return, inventory accountability, and back-office control.</p><div className="auth-features"><span><Icon name="scan"/>Barcode accountability</span><span><Icon name="warehouse"/>Warehouse control</span><span><Icon name="shield"/>Role-based access</span></div></section><section className="auth-card"><span className="kicker">SECURE ACCESS</span><h2>{mode==="setup"?"Create Admin PIN":loginType==="admin"?"Super Admin PIN":"Staff Login"}</h2><p>{mode==="setup"?"One-time activation: create your own 6-digit Super Admin PIN.":loginType==="admin"?"Enter your private 6-digit PIN.":"Enter the username and password created by your administrator."}</p>{mode==="login"&&<div className="auth-tabs">{setupRequired?<button type="button" onClick={()=>{setMode("setup");setError("")}}>Create Admin PIN First</button>:<button type="button" className={loginType==="admin"?"active":""} onClick={()=>{setLoginType("admin");setError("")}}>Admin PIN</button>}<button type="button" className={loginType==="staff"?"active":""} onClick={()=>{setLoginType("staff");setError("")}}>Staff Login</button></div>}{error&&<div className="auth-error">{error}</div>}<form onSubmit={submit}>
    {adminAccess?<input name="username" type="hidden" value="stefan" readOnly/>:<label>Username<input name="username" required autoComplete="username" placeholder="Staff username"/></label>}
    {mode==="setup"&&<label>One-Time Activation Code<input name="activationCode" required autoComplete="one-time-code" placeholder="Activation code"/></label>}
    {mode==="setup"?<label>Create 6-Digit PIN<input name="pin" required type="password" inputMode="numeric" pattern="[0-9]{6}" minLength={6} maxLength={6} autoComplete="new-password" placeholder="••••••"/></label>:adminAccess?<label>6-Digit Admin PIN<input name="password" required type="password" inputMode="numeric" pattern="[0-9]{6}" minLength={6} maxLength={6} autoComplete="current-password" placeholder="••••••"/></label>:<label>Password<input name="password" required type="password" minLength={10} autoComplete="current-password" placeholder="••••••••••"/></label>}
    {mode==="setup"&&<small className="password-help">Choose six numbers that only the Super Admin knows.</small>}
    <button className="btn primary full" disabled={busy}>{busy?"Please wait…":mode==="setup"?"Activate Admin PIN":loginType==="admin"?"Login with PIN":"Staff Login"}</button>
  </form>{setupRequired&&<button className="auth-switch" onClick={()=>{setError("");setMode(mode==="setup"?"login":"setup");setLoginType("staff")}}>{mode==="setup"?"Go to staff login":"Create Super Admin PIN"}</button>}<footer><Icon name="shield"/> Session expires automatically after 8 hours</footer></section></main>;
}

function MetricCard({label,value,detail,tone="silver",icon}:{label:string;value:string|number;detail:string;tone?:string;icon:string}) { return <article className={`metric ${tone}`}><span className="metric-icon"><Icon name={icon}/></span><div><small>{label}</small><strong>{value}</strong><p>{detail}</p></div></article>; }
function PageHead({kicker,title,sub,actions}:{kicker:string;title:string;sub:string;actions?:React.ReactNode}) { return <div className="page-head"><div><span className="kicker">{kicker}</span><h1>{title}</h1><p>{sub}</p></div>{actions&&<div className="page-actions">{actions}</div>}</div>; }

function OperationalEquipment({inventory,filtered,search,setSearch,status,setStatus,category,setCategory,setShowAdd,print,preview,remove,submitting}:{inventory:InventoryData;filtered:Asset[];search:string;setSearch:(s:string)=>void;status:string;setStatus:(s:string)=>void;category:string;setCategory:(s:string)=>void;setShowAdd:(b:boolean)=>void;print:()=>void;preview:(a:Asset)=>void;remove:(a:Asset)=>void;submitting:boolean}) {
  const categories=[...new Set(inventory.items.map(a=>a.category))];
  return <><PageHead kicker="ASSET MANAGEMENT" title="Equipment Inventory" sub="Search, filter, label, and manage every registered equipment unit." actions={<><button className="btn secondary" onClick={print}><Icon name="print"/>Print Labels</button><button className="btn primary" onClick={()=>setShowAdd(true)}><Icon name="plus"/>Add Equipment</button></>}/>
    <div className="submetrics"><span><b>{inventory.summary.total}</b>Total units</span><span><b>{inventory.summary.available}</b>Warehouse</span><span><b>{inventory.summary.pulledOut}</b>Deployed</span><span><b>{inventory.summary.returnedToday}</b>Returned today</span></div>
    <article className="panel data-panel"><div className="table-tools"><div className="search-box"><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search ID, equipment, category, event…"/></div><select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Equipment status"><option value="all">All status</option><option value="available">Available</option><option value="pulled_out">Pulled out</option></select><select value={category} onChange={e=>setCategory(e.target.value)} aria-label="Equipment category"><option value="all">All categories</option>{categories.map(c=><option key={c} value={c}>{c}</option>)}</select></div>
      <div className="table-scroll"><table><thead><tr><th>Equipment ID</th><th>Equipment</th><th>Category</th><th>Storage</th><th>Condition</th><th>Status</th><th>Assigned Event</th><th>Actions</th></tr></thead><tbody>{filtered.map((a,i)=><tr key={a.id}><td><code>{a.assetCode}</code></td><td><div className="equipment-cell"><span className="equip-thumb"><Icon name="box"/></span><div><b>{a.name}</b><small>Stageability Asset</small></div></div></td><td>{a.category}</td><td>{["Rack A-01","Lighting Bay","LED Storage","Truss Zone"][i%4]}</td><td><Status value="Good"/></td><td><Status value={a.status==="available"?"Available":"Pulled Out"}/></td><td>{a.currentEvent||<span className="muted">—</span>}</td><td><div className="row-actions"><button onClick={()=>preview(a)} title="Generate barcode"><Icon name="scan"/>Barcode</button><button onClick={()=>{preview(a);window.setTimeout(()=>{document.body.classList.add("print-one-label");window.print();window.setTimeout(()=>document.body.classList.remove("print-one-label"),200)},120)}} title="Print this barcode"><Icon name="print"/>Print</button><button className="danger" disabled={submitting||a.status==="pulled_out"} onClick={()=>remove(a)} title={a.status==="pulled_out"?"Return this item before deleting":"Delete equipment"}><Icon name="trash"/>Delete</button></div></td></tr>)}{!filtered.length&&<tr><td colSpan={8} className="empty-cell">No equipment matches the selected filters.</td></tr>}</tbody></table></div>
    </article></>;
}

function OperationalEvents({data,open}:{data:BackOfficeData;open:()=>void}) {
  return <><PageHead kicker="EVENT OPERATIONS" title="Event Calendar & Bookings" sub="Plan schedules, venues, crew assignments, equipment reservations, and event status." actions={<button className="btn primary" onClick={open}><Icon name="plus"/>New Event</button>}/><div className="event-board">{data.events.map(e=><article className="event-card" key={e.id}><div className="event-date"><b>{new Date(e.eventDate+"T00:00:00").getDate()}</b><span>{new Date(e.eventDate+"T00:00:00").toLocaleDateString("en-PH",{month:"short"}).toUpperCase()}</span><small>{new Date(e.eventDate+"T00:00:00").getFullYear()}</small></div><div className="event-info"><div><code>{e.eventCode}</code><Status value={e.status}/></div><h3>{e.title}</h3><p>{e.clientName}</p><span><Icon name="warehouse"/> {e.venue}</span><footer><small><Icon name="users"/> {e.crewCount} crew</small><small><Icon name="box"/> {e.equipmentCount} equipment</small></footer></div></article>)}</div>
    <article className="panel data-panel"><div className="panel-title"><div><span className="kicker">BOOKING SCHEDULE</span><h2>All Events</h2></div><small className="muted">{data.events.length} bookings</small></div><div className="table-scroll"><table><thead><tr><th>Date</th><th>Event</th><th>Client</th><th>Venue</th><th>Crew</th><th>Equipment</th><th>Status</th></tr></thead><tbody>{data.events.map(e=><tr key={e.id}><td>{e.eventDate}</td><td><b>{e.title}</b><small className="block">{e.eventCode}</small></td><td>{e.clientName}</td><td>{e.venue}</td><td>{e.crewCount}</td><td>{e.equipmentCount}</td><td><Status value={e.status}/></td></tr>)}</tbody></table></div></article></>;
}

function OperationalClients({data,openClient,openQuote}:{data:BackOfficeData;openClient:()=>void;openQuote:()=>void}) {
  return <><PageHead kicker="CLIENT RELATIONSHIP MANAGEMENT" title="Clients, Quotations & Billing" sub="Add clients and quotations to the shared cloud database." actions={<><button className="btn secondary" onClick={openQuote}><Icon name="report"/>New Quotation</button><button className="btn primary" onClick={openClient}><Icon name="plus"/>New Client</button></>}/><div className="client-stats"><MetricCard label="ACTIVE CLIENTS" value={data.clients.length} detail="in current database" icon="users"/><MetricCard label="PENDING QUOTATIONS" value={data.quotations.filter(q=>q.status==="pending").length} detail="requires follow-up" icon="report" tone="amber"/><MetricCard label="ACCOUNTS RECEIVABLE" value={peso.format(data.clients.reduce((s,c)=>s+c.balance,0))} detail="outstanding balances" icon="wallet" tone="red"/></div>
    <div className="two-cols"><article className="panel data-panel"><div className="panel-title"><div><span className="kicker">CLIENT DATABASE</span><h2>Client Accounts</h2></div></div><div className="table-scroll"><table><thead><tr><th>Client</th><th>Client ID</th><th>Contact</th><th>Balance</th><th>Status</th></tr></thead><tbody>{data.clients.map(c=><tr key={c.id}><td><div className="person-cell"><Avatar name={c.name}/><div><b>{c.name}</b><small>{c.company||"Individual client"}</small></div></div></td><td><code>{c.clientCode}</code></td><td><span>{c.contact}</span><small className="block">{c.email||"No email"}</small></td><td className={c.balance>0?"money-due":""}>{peso.format(c.balance)}</td><td><Status value={c.balance>0?"Outstanding":"Paid"}/></td></tr>)}</tbody></table></div></article>
      <article className="panel quote-panel"><div className="panel-title"><div><span className="kicker">SALES PIPELINE</span><h2>Latest Quotations</h2></div><button className="text-btn" onClick={openQuote}>+ Add</button></div>{data.quotations.map(q=><div className="quote-row" key={q.id}><div><code>{q.quoteNo}</code><b>{q.eventName}</b><small>{q.clientName}</small></div><div><strong>{peso.format(q.amount)}</strong><Status value={q.status}/></div></div>)}</article></div></>;
}

function OperationalStaff({data,open,openStaff}:{data:BackOfficeData;open:()=>void;openStaff:(staff:Staff)=>void}) {
  const roles=["Super Admin","Admin","Office Staff","Warehouse Staff","Technician","Crew"];
  return <><PageHead kicker="PEOPLE & ACCOUNTABILITY" title="Staff & User Management" sub="Create role-based staff records and update attendance, account status, and 2FA enrollment." actions={<button className="btn primary" onClick={open}><Icon name="plus"/>Add Staff Account</button>}/><div className="staff-summary"><div><b>{data.metrics.attendancePresent}/{data.metrics.attendanceTotal}</b><span>Present / On-site</span></div>{roles.map(r=><div key={r}><b>{data.staff.filter(s=>s.role===r).length}</b><span>{r}</span></div>)}</div><div className="staff-grid">{data.staff.map(s=><article className="staff-card" key={s.id}><div className="staff-top"><Avatar name={s.fullName}/><div><Status value={s.attendanceStatus}/><span className={`security-dot ${s.twoFactorEnabled?"on":"off"}`} title={s.twoFactorEnabled?"2FA enabled":"2FA pending"}/></div></div><h3>{s.fullName}</h3><p>{s.position}</p><code>{s.employeeId}</code><dl><div><dt>Role</dt><dd>{s.role}</dd></div><div><dt>Username</dt><dd>{s.username}</dd></div><div><dt>Contact</dt><dd>{s.contactNumber}</dd></div><div><dt>Account</dt><dd>{s.accountStatus}</dd></div></dl><footer><span><Icon name="shield"/>{s.twoFactorEnabled?"2FA Enabled":"2FA Pending"}</span><button onClick={()=>openStaff(s)} aria-label={`Update ${s.fullName}`}><Icon name="eye"/></button></footer></article>)}</div></>;
}

function OperationalFinance({data,open}:{data:BackOfficeData;open:()=>void}) {
  const income=data.finance.filter(f=>f.type==="income").reduce((s,f)=>s+f.amount,0), expenses=data.finance.filter(f=>f.type==="expense").reduce((s,f)=>s+f.amount,0), margin=income?Math.round((income-expenses)/income*100):0;
  return <><PageHead kicker="FINANCIAL CONTROL" title="Finance & Accounting" sub="Record income and expenses and monitor profitability and receivables." actions={<button className="btn primary" onClick={open}><Icon name="plus"/>New Transaction</button>}/><div className="finance-metrics"><MetricCard label="MONTHLY INCOME" value={peso.format(income)} detail="posted transactions" icon="wallet" tone="green"/><MetricCard label="MONTHLY EXPENSES" value={peso.format(expenses)} detail="operating costs" icon="wallet" tone="red"/><MetricCard label="NET PROFIT" value={peso.format(income-expenses)} detail={`${margin}% margin`} icon="report" tone="blue"/><MetricCard label="RECEIVABLES" value={peso.format(data.clients.reduce((s,c)=>s+c.balance,0))} detail="client balances" icon="users" tone="amber"/></div><article className="panel data-panel"><div className="panel-title"><div><span className="kicker">GENERAL LEDGER</span><h2>Recorded Transactions</h2></div><button className="text-btn" onClick={open}>+ Add transaction</button></div><div className="table-scroll"><table><thead><tr><th>Date</th><th>Type</th><th>Category</th><th>Description</th><th>Event</th><th>Amount</th></tr></thead><tbody>{data.finance.map(f=><tr key={f.id}><td>{f.entryDate}</td><td><Status value={f.type}/></td><td>{f.category}</td><td><b>{f.description}</b></td><td>{f.eventName||"—"}</td><td className={f.type==="income"?"money-in":"money-out"}>{f.type==="income"?"+":"−"}{peso.format(f.amount)}</td></tr>)}</tbody></table></div></article></>;
}

function OperationalWarehouse({data,open}:{data:BackOfficeData;open:()=>void}) {
  return <><PageHead kicker="WAREHOUSE CONTROL" title="Stock & Consumables" sub="Apply stock-in, stock-out, and correction adjustments with automatic totals." actions={<button className="btn primary" onClick={open}><Icon name="plus"/>Stock Adjustment</button>}/><div className="warehouse-layout"><article className="panel data-panel"><div className="panel-title"><div><span className="kicker">LIVE STOCK</span><h2>Consumables Inventory</h2></div><span className="stock-alert">{data.warehouse.filter(w=>w.stock<=w.minStock).length} low-stock items</span></div><div className="table-scroll"><table><thead><tr><th>Item Code</th><th>Item</th><th>Category</th><th>Stock Level</th><th>Minimum</th><th>Supplier</th><th>Status</th></tr></thead><tbody>{data.warehouse.map(w=>{const low=w.stock<=w.minStock;return <tr key={w.id}><td><code>{w.itemCode}</code></td><td><b>{w.name}</b></td><td>{w.category}</td><td><div className="stock-level"><span>{w.stock} {w.unit}</span><i><em className={low?"low":""} style={{width:`${Math.min(100,w.stock/Math.max(w.minStock*2,1)*100)}%`}}/></i></div></td><td>{w.minStock} {w.unit}</td><td>{w.supplier}</td><td><Status value={low?"Low Stock":"In Stock"}/></td></tr>})}</tbody></table></div></article><aside className="warehouse-side"><article className="panel mini-panel"><span className="kicker">TOTAL STOCK</span><h3>Recorded Units</h3><b className="big-number">{data.warehouse.reduce((s,w)=>s+w.stock,0)}</b><p>Across {data.warehouse.length} consumable items</p></article><article className="panel mini-panel"><span className="kicker">LOW STOCK</span><h3>Needs Reordering</h3><b className="big-number">{data.warehouse.filter(w=>w.stock<=w.minStock).length}</b><p>At or below minimum level</p></article><article className="panel mini-panel"><span className="kicker">SUPPLIERS</span><h3>Current Sources</h3><b className="big-number">{new Set(data.warehouse.map(w=>w.supplier)).size}</b><p>Linked to inventory records</p></article></aside></div></>;
}

function OperationalNotifications({data,mark,submitting}:{data:BackOfficeData;mark:(id?:number)=>void;submitting:boolean}) {
  const [filter,setFilter]=useState("all");
  const rows=data.notifications.filter(n=>filter==="all"||(filter==="unread"?!n.isRead:n.type===filter));
  const filters=[{id:"all",label:"All notifications"},{id:"unread",label:"Unread"},{id:"stock",label:"Low stock"},{id:"maintenance",label:"Maintenance"},{id:"event",label:"Upcoming events"},{id:"balance",label:"Outstanding balances"}];
  return <><PageHead kicker="ALERT CENTER" title="Notifications & Reminders" sub="Filter alerts and mark individual or all notifications as read." actions={<button className="btn secondary" disabled={submitting||!data.notifications.some(n=>!n.isRead)} onClick={()=>mark()}><Icon name="shield"/>Mark all as read</button>}/><div className="notification-layout"><article className="panel notification-list">{rows.map(n=><div key={n.id} className={`notification ${n.severity} ${n.isRead?"read":""}`}><span><Icon name={n.type==="event"?"calendar":n.type==="balance"?"wallet":"bell"}/></span><div><div><b>{n.title}</b><Status value={n.isRead?"Read":n.severity}/></div><p>{n.message}</p><small>Due {n.dueDate||"—"}</small></div><button disabled={submitting||Boolean(n.isRead)} onClick={()=>mark(n.id)} aria-label={`Mark ${n.title} as read`}>{n.isRead?"✓":"Mark read"}</button></div>)}{!rows.length&&<p className="empty-state">No notifications in this filter.</p>}</article><aside className="panel notification-filter"><span className="kicker">FILTERS</span>{filters.map(x=><button className={filter===x.id?"active":""} onClick={()=>setFilter(x.id)} key={x.id}>{x.label}<span>{x.id==="all"?data.notifications.length:x.id==="unread"?data.notifications.filter(n=>!n.isRead).length:data.notifications.filter(n=>n.type===x.id).length}</span></button>)}</aside></div></>;
}

export default function Home() {
  const [view,setView]=useState<View>("dashboard"); const [mobileOpen,setMobileOpen]=useState(false); const [inventory,setInventory]=useState<InventoryData|null>(null); const [back,setBack]=useState<BackOfficeData|null>(null); const [loading,setLoading]=useState(true); const [notice,setNotice]=useState(""); const [search,setSearch]=useState(""); const [globalSearch,setGlobalSearch]=useState(""); const [statusFilter,setStatusFilter]=useState("all"); const [categoryFilter,setCategoryFilter]=useState("all"); const [scanMode,setScanMode]=useState<"pullout"|"return"|null>(null); const [eventName,setEventName]=useState(""); const [operatorName,setOperatorName]=useState(""); const [showAdd,setShowAdd]=useState(false); const [barcodeAsset,setBarcodeAsset]=useState<Asset|null>(null); const [modal,setModal]=useState<ModalKind|null>(null); const [selectedStaff,setSelectedStaff]=useState<Staff|null>(null); const [submitting,setSubmitting]=useState(false);
  const [authUser,setAuthUser]=useState<AuthUser|null>(null); const [authReady,setAuthReady]=useState(false); const [setupNeeded,setSetupNeeded]=useState(false);
  const isAdmin=Boolean(authUser&&["Super Admin","Admin"].includes(authUser.role));
  const allowedNav=useMemo(()=>isAdmin?nav:nav.filter(n=>n.id==="pullout"||n.id==="warehouse"),[isAdmin]);
  const load=useCallback(async()=>{try{const [i,b]=await Promise.all([fetch("/api/inventory",{cache:"no-store"}),fetch("/api/backoffice",{cache:"no-store"})]);const [id,bd]=await Promise.all([i.json(),b.json()]);if(i.status===401||b.status===401){setAuthUser(null);throw new Error("Your session expired. Please sign in again.")}if(!i.ok)throw new Error(id.error);if(!b.ok)throw new Error(bd.error);setInventory(id);setBack(bd);}catch(e){setNotice(e instanceof Error?e.message:"Unable to load back-office data.");}finally{setLoading(false)}},[]);
  useEffect(()=>{let active=true;(async()=>{try{const r=await fetch("/api/auth",{cache:"no-store"});const body=await r.json();if(!active)return;setAuthUser(body.user??null);setSetupNeeded(Boolean(body.setupRequired));if(body.user){setOperatorName(body.user.fullName);setView(["Super Admin","Admin"].includes(body.user.role)?"dashboard":"pullout")}}catch{if(active)setNotice("Unable to check your staff session.")}finally{if(active)setAuthReady(true)}})();return()=>{active=false}},[]);
  useEffect(()=>{if(!authUser)return;const t=window.setTimeout(()=>{setLoading(true);void load()},0);return()=>window.clearTimeout(t)},[authUser,load]);
  const changeView=(id:View)=>{setView(!isAdmin&&id!=="pullout"&&id!=="warehouse"?"pullout":id);setMobileOpen(false);window.scrollTo({top:0,behavior:"smooth"})};
  const unread=back?.notifications.filter(n=>!n.isRead).length??0;
  const filteredAssets=useMemo(()=>(inventory?.items??[]).filter(a=>`${a.assetCode} ${a.name} ${a.category} ${a.currentEvent??""}`.toLowerCase().includes(search.toLowerCase())&&(statusFilter==="all"||a.status===statusFilter)&&(categoryFilter==="all"||a.category===categoryFilter)),[inventory,search,statusFilter,categoryFilter]);
  const handleCode=useCallback(async(code:string)=>{if(!scanMode)return;setScanMode(null);setSubmitting(true);try{const r=await fetch("/api/scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assetCode:code,action:scanMode,eventName,operatorName})});const body=await r.json();if(!r.ok)throw new Error(body.error);setNotice(`${body.asset.name} (${body.asset.assetCode}) ${scanMode==="pullout"?"released for event":"returned to warehouse"}.`);await load();}catch(e){setNotice(e instanceof Error?e.message:"Scan failed.");}finally{setSubmitting(false)}},[scanMode,eventName,operatorName,load]);
  async function addAsset(e:FormEvent<HTMLFormElement>){e.preventDefault();setSubmitting(true);const form=new FormData(e.currentTarget);try{const r=await fetch("/api/inventory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(form))});const body=await r.json();if(!r.ok)throw new Error(body.error);setShowAdd(false);setNotice(`${body.asset.assetCode} added to inventory.`);await load();}catch(err){setNotice(err instanceof Error?err.message:"Unable to add equipment.");}finally{setSubmitting(false)}}
  async function removeAsset(asset:Asset){if(!window.confirm(`Delete ${asset.name} (${asset.assetCode})? This cannot be undone.`))return;setSubmitting(true);try{const r=await fetch("/api/inventory",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:asset.id})});const body=await r.json();if(!r.ok)throw new Error(body.error);setNotice(`${asset.assetCode} deleted from inventory.`);await load();}catch(err){setNotice(err instanceof Error?err.message:"Unable to delete equipment.");}finally{setSubmitting(false)}}
  async function saveBackOffice(e:FormEvent<HTMLFormElement>,kind:ModalKind){e.preventDefault();setSubmitting(true);const values=Object.fromEntries(new FormData(e.currentTarget));const method=kind==="staff-edit"?"PATCH":"POST";const resource=kind==="staff-edit"?"staff":kind;try{const r=await fetch("/api/backoffice",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify({resource,...values,twoFactorEnabled:values.twoFactorEnabled==="on"})});const body=await r.json();if(!r.ok)throw new Error(body.error);setModal(null);setSelectedStaff(null);setNotice(`${kind.replace("-edit","").replace(/^./,x=>x.toUpperCase())} saved successfully.`);await load();}catch(err){setNotice(err instanceof Error?err.message:"Unable to save record.");}finally{setSubmitting(false)}}
  async function markNotification(id?:number){setSubmitting(true);try{const r=await fetch("/api/backoffice",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource:"notification",id})});const body=await r.json();if(!r.ok)throw new Error(body.error);setNotice(id?"Notification marked as read.":"All notifications marked as read.");await load();}catch(err){setNotice(err instanceof Error?err.message:"Unable to update notification.");}finally{setSubmitting(false)}}
  function openStaff(staff:Staff){setSelectedStaff(staff);setModal("staff-edit")}
  function runGlobalSearch(e:FormEvent<HTMLFormElement>){e.preventDefault();const q=globalSearch.trim().toLowerCase();if(!q||!back||!inventory)return;const asset=inventory.items.find(a=>`${a.assetCode} ${a.name} ${a.category}`.toLowerCase().includes(q));if(asset){setSearch(globalSearch);changeView("equipment");return;}if(back.clients.some(c=>`${c.name} ${c.company} ${c.clientCode}`.toLowerCase().includes(q))){changeView("clients");return;}if(back.events.some(x=>`${x.title} ${x.clientName} ${x.venue}`.toLowerCase().includes(q))){changeView("events");return;}if(back.staff.some(s=>`${s.fullName} ${s.employeeId} ${s.position}`.toLowerCase().includes(q))){changeView("staff");return;}setNotice(`No record found for “${globalSearch}”.`)}
  function exportCsv(name:string,rows:Record<string,unknown>[]){if(!rows.length)return;const keys=Object.keys(rows[0]);const esc=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const csv=[keys.join(","),...rows.map(r=>keys.map(k=>esc(r[k])).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`stageability-${name}.csv`;a.click();URL.revokeObjectURL(a.href);}
  function printLabels(){document.body.classList.add("print-labels");window.print();window.setTimeout(()=>document.body.classList.remove("print-labels"),200)}
  const currentTitle=allowedNav.find(n=>n.id===view)?.label??"Pull-Out & Return";
  function authenticated(user:AuthUser){setAuthUser(user);setSetupNeeded(false);setOperatorName(user.fullName);setView(["Super Admin","Admin"].includes(user.role)?"dashboard":"pullout");setLoading(true)}
  async function signOut(){setSubmitting(true);try{await fetch("/api/auth",{method:"DELETE"})}finally{setAuthUser(null);setInventory(null);setBack(null);setNotice("");setMobileOpen(false);setSubmitting(false)}}

  if(!authReady)return <main className="auth-loading"><span/><h1>Stageability</h1><p>Checking secure staff access…</p></main>;
  if(!authUser)return <AuthScreen setupRequired={setupNeeded} onAuth={authenticated}/>;

  return <main className="backoffice">
    <aside className={`sidebar ${mobileOpen?"open":""}`}>
      <div className="side-brand"><img className="brand-mark" src="/stageability-logo.jpg" alt="Stageability logo"/><div><b>STAGEABILITY</b><small>LIGHTS &amp; SOUNDS</small></div><button className="side-close" onClick={()=>setMobileOpen(false)} aria-label="Close menu"><Icon name="close"/></button></div>
      <div className="workspace-label"><span>{isAdmin?"BACK OFFICE":"STAFF OPERATIONS"}</span><i>LIVE</i></div>
      <nav>{["OPERATIONS","BUSINESS","CONTROL"].map(group=>{const items=allowedNav.filter(n=>n.group===group);return items.length?<div className="nav-group" key={group}><small>{group}</small>{items.map(n=><button key={n.id} className={view===n.id?"active":""} onClick={()=>changeView(n.id)}><Icon name={n.icon}/><span>{n.label}</span>{n.id==="notifications"&&unread>0&&<em>{unread}</em>}</button>)}</div>:null})}</nav>
      <div className="side-user"><Avatar name={authUser.fullName}/><div><b>{authUser.fullName}</b><small>{authUser.role}</small></div><button className="logout-btn" onClick={signOut} disabled={submitting}>Log out</button></div>
    </aside>
    {mobileOpen&&<button className="nav-scrim" onClick={()=>setMobileOpen(false)} aria-label="Close menu"/>}

    <div className="app-main">
      <header className="app-header"><button className="menu-btn" onClick={()=>setMobileOpen(true)} aria-label="Open menu"><Icon name="menu"/></button><div className="header-title"><span>{isAdmin?"Stageability Back Office":"Stageability Staff Operations"}</span><b>{currentTitle}</b></div>{isAdmin&&<form className="global-search" onSubmit={runGlobalSearch}><Icon name="search"/><input value={globalSearch} onChange={e=>setGlobalSearch(e.target.value)} placeholder="Search equipment, clients, events…" aria-label="Global search"/></form>}<div className="header-tools"><span className="cloud-state"><i/> Cloud synced</span>{isAdmin&&<button className="notify-btn" onClick={()=>changeView("notifications")} aria-label="Notifications"><Icon name="bell"/>{unread>0&&<em>{unread}</em>}</button>}<Avatar name={authUser.fullName}/></div></header>
      {notice&&<div className={`toast ${notice.includes("failed")||notice.includes("not")?"bad":""}`}><Icon name="bell"/>{notice}<button onClick={()=>setNotice("")} aria-label="Dismiss"><Icon name="close" size={15}/></button></div>}
      <section className="workspace">
        {loading?<div className="loading"><span/><h2>Loading Stageability Back Office</h2><p>Syncing cloud inventory and business records…</p></div>:<>
          {isAdmin&&view==="dashboard"&&<Dashboard inventory={inventory!} back={back!} go={changeView}/>} 
          {isAdmin&&view==="equipment"&&<OperationalEquipment inventory={inventory!} filtered={filteredAssets} search={search} setSearch={setSearch} status={statusFilter} setStatus={setStatusFilter} category={categoryFilter} setCategory={setCategoryFilter} setShowAdd={setShowAdd} print={printLabels} preview={setBarcodeAsset} remove={removeAsset} submitting={submitting}/>} 
          {view==="pullout"&&<Pullout inventory={inventory!} back={back!} eventName={eventName} setEventName={setEventName} operatorName={operatorName} setOperatorName={setOperatorName} scan={setScanMode} submitting={submitting}/>} 
          {isAdmin&&view==="events"&&<OperationalEvents data={back!} open={()=>setModal("event")}/>} {isAdmin&&view==="clients"&&<OperationalClients data={back!} openClient={()=>setModal("client")} openQuote={()=>setModal("quotation")}/>} {isAdmin&&view==="staff"&&<OperationalStaff data={back!} open={()=>setModal("staff")} openStaff={openStaff}/>} 
          {isAdmin&&view==="finance"&&<OperationalFinance data={back!} open={()=>setModal("finance")}/>} {view==="warehouse"&&<OperationalWarehouse data={back!} open={()=>setModal("stock")}/>} 
          {isAdmin&&view==="reports"&&<Reports inventory={inventory!} back={back!} exportCsv={exportCsv}/>} {isAdmin&&view==="notifications"&&<OperationalNotifications data={back!} mark={markNotification} submitting={submitting}/>} {isAdmin&&view==="security"&&<Security data={back!}/>} 
        </>}
      </section>
    </div>
    {scanMode&&<Scanner onCode={handleCode} onClose={()=>setScanMode(null)}/>} 
    {barcodeAsset&&<div className="modal-backdrop barcode-modal" role="dialog" aria-modal="true" aria-label="Generated barcode"><div className="barcode-preview-card"><div className="modal-head"><div><span className="kicker">GENERATED CODE128 BARCODE</span><h2>{barcodeAsset.name}</h2></div><button className="icon-btn" onClick={()=>setBarcodeAsset(null)} aria-label="Close"><Icon name="close"/></button></div><div className="barcode-label"><img src="/stageability-logo.jpg" alt="Stageability logo"/><b>STAGEABILITY LIGHTS &amp; SOUNDS</b><span>{barcodeAsset.name}</span><small>{barcodeAsset.category}</small><Barcode value={barcodeAsset.assetCode}/></div><div className="form-actions"><button className="btn secondary" onClick={()=>setBarcodeAsset(null)}>Close</button><button className="btn primary" onClick={()=>{document.body.classList.add("print-one-label");window.print();window.setTimeout(()=>document.body.classList.remove("print-one-label"),200)}}><Icon name="print"/>Print Barcode</button></div></div></div>}
    {modal&&back&&<BackOfficeModal kind={modal} data={back} staff={selectedStaff} onClose={()=>{setModal(null);setSelectedStaff(null)}} onSubmit={saveBackOffice} submitting={submitting}/>} 
    {showAdd&&<div className="modal-backdrop" role="dialog" aria-modal="true"><form className="form-card" onSubmit={addAsset}><div className="modal-head"><div><span className="kicker">NEW ASSET</span><h2>Add equipment</h2></div><button type="button" className="icon-btn" onClick={()=>setShowAdd(false)}><Icon name="close"/></button></div><label>Unique equipment ID<input name="assetCode" required placeholder="SA-SPK-005"/></label><label>Equipment name<input name="name" required placeholder="Active Speaker 15-inch"/></label><label>Category<select name="category" defaultValue="Sound"><option>Sound</option><option>Lighting</option><option>LED Wall</option><option>Staging</option><option>Truss</option><option>Band Equipment</option><option>Power</option><option>Cables & Accessories</option></select></label><button className="btn primary full" disabled={submitting}>{submitting?"Saving…":"Save Equipment"}</button></form></div>}
    <section className="print-sheet"><h1>STAGEABILITY LIGHTS &amp; SOUNDS — ASSET LABELS</h1><div className="labels">{inventory?.items.map(a=><article className="asset-label" key={a.id}><b>STAGEABILITY</b><span>{a.name}</span><Barcode value={a.assetCode}/></article>)}</div></section>
  </main>;
}

function Dashboard({inventory,back,go}:{inventory:InventoryData;back:BackOfficeData;go:(v:View)=>void}) {
  const active=back.events.filter(e=>["confirmed","preparation"].includes(e.status)).length; const pending=back.quotations.filter(q=>q.status==="pending").length; const maintenance=back.maintenance.filter(m=>m.status!=="completed").length;
  return <><PageHead kicker="EXECUTIVE OVERVIEW" title="Operations Dashboard" sub="Live equipment, events, people, and financial performance in one command center." actions={<><button className="btn secondary" onClick={()=>go("reports")}><Icon name="report"/>Generate Report</button><button className="btn primary" onClick={()=>go("pullout")}><Icon name="scan"/>Quick Scan</button></>}/>
    <div className="metric-grid"><MetricCard label="TOTAL EQUIPMENT" value={inventory.summary.total} detail="registered assets" icon="box"/><MetricCard label="AVAILABLE" value={inventory.summary.available} detail="ready in warehouse" icon="back" tone="green"/><MetricCard label="RESERVED" value={9} detail="for upcoming events" icon="calendar" tone="blue"/><MetricCard label="PULLED OUT" value={inventory.summary.pulledOut} detail="currently deployed" icon="out" tone="red"/><MetricCard label="MAINTENANCE" value={maintenance} detail="requires attention" icon="shield" tone="amber"/><MetricCard label="ACTIVE EVENTS" value={active} detail="confirmed & preparing" icon="calendar" tone="violet"/><MetricCard label="MONTHLY REVENUE" value={peso.format(back.metrics.monthlyRevenue)} detail="July 2026" icon="wallet" tone="green"/><MetricCard label="PENDING QUOTES" value={pending} detail="awaiting client action" icon="report" tone="amber"/><MetricCard label="ATTENDANCE" value={`${back.metrics.attendancePresent}/${back.metrics.attendanceTotal}`} detail="present or on-site" icon="badge" tone="silver"/></div>
    <div className="dashboard-grid"><article className="panel chart-card"><div className="panel-title"><div><span className="kicker">FINANCIAL ANALYTICS</span><h2>Revenue Performance</h2></div><select aria-label="Revenue period"><option>Last 6 months</option></select></div><div className="chart-summary"><div><small>TOTAL REVENUE</small><b>{peso.format(428500)}</b><span className="up">↑ 18.4%</span></div><div><small>NET PROFIT</small><b>{peso.format(314600)}</b><span>73.4% margin</span></div></div><RevenueChart/></article>
      <article className="panel utilization"><div className="panel-title"><div><span className="kicker">ASSET HEALTH</span><h2>Equipment Utilization</h2></div><button className="text-btn" onClick={()=>go("equipment")}>View all →</button></div><div className="donut-wrap"><div className="donut"><span><b>76%</b><small>UTILIZED</small></span></div><div className="legend"><p><i className="lg-green"/>Available <b>{inventory.summary.available}</b></p><p><i className="lg-red"/>Pulled Out <b>{inventory.summary.pulledOut}</b></p><p><i className="lg-blue"/>Reserved <b>9</b></p><p><i className="lg-amber"/>Maintenance <b>2</b></p></div></div></article>
      <article className="panel events-card"><div className="panel-title"><div><span className="kicker">BOOKING PIPELINE</span><h2>Upcoming Events</h2></div><button className="text-btn" onClick={()=>go("events")}>Full calendar →</button></div><div className="event-list">{back.events.slice(0,4).map(e=><div key={e.id}><time><b>{new Date(e.eventDate+"T00:00:00").toLocaleDateString("en-PH",{day:"2-digit"})}</b><span>{new Date(e.eventDate+"T00:00:00").toLocaleDateString("en-PH",{month:"short"}).toUpperCase()}</span></time><div><b>{e.title}</b><p>{e.venue}</p><small>{e.crewCount} crew • {e.equipmentCount} equipment</small></div><Status value={e.status}/></div>)}</div></article>
      <article className="panel alert-card"><div className="panel-title"><div><span className="kicker">ACTION REQUIRED</span><h2>Priority Alerts</h2></div><button className="text-btn" onClick={()=>go("notifications")}>{back.notifications.length} alerts →</button></div><div className="alert-list">{back.notifications.slice(0,4).map(n=><div key={n.id} className={n.severity}><span className="alert-icon"><Icon name={n.type==="event"?"calendar":n.type==="balance"?"wallet":"bell"}/></span><div><b>{n.title}</b><p>{n.message}</p></div></div>)}</div></article>
    </div></>;
}

function RevenueChart(){return <div className="revenue-chart"><div className="chart-lines"><i/><i/><i/><i/></div><svg viewBox="0 0 600 190" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#e23a3f" stopOpacity=".35"/><stop offset="1" stopColor="#e23a3f" stopOpacity="0"/></linearGradient></defs><path className="area" d="M0 155 C60 140 80 128 120 134 S190 105 240 113 S310 78 360 88 S430 52 480 65 S550 28 600 35 L600 190 L0 190Z"/><path className="line" d="M0 155 C60 140 80 128 120 134 S190 105 240 113 S310 78 360 88 S430 52 480 65 S550 28 600 35"/></svg><div className="chart-months"><span>FEB</span><span>MAR</span><span>APR</span><span>MAY</span><span>JUN</span><span>JUL</span></div></div>}

function Equipment({inventory,filtered,search,setSearch,status,setStatus,setShowAdd,print}:{inventory:InventoryData;filtered:Asset[];search:string;setSearch:(s:string)=>void;status:string;setStatus:(s:string)=>void;setShowAdd:(b:boolean)=>void;print:()=>void}) {return <><PageHead kicker="ASSET MANAGEMENT" title="Equipment Inventory" sub="Track every unit by barcode, category, condition, storage location, and deployment status." actions={<><button className="btn secondary" onClick={print}><Icon name="print"/>Print Labels</button><button className="btn primary" onClick={()=>setShowAdd(true)}><Icon name="plus"/>Add Equipment</button></>}/><div className="submetrics"><span><b>{inventory.summary.total}</b>Total units</span><span><b>{inventory.summary.available}</b>Warehouse</span><span><b>{inventory.summary.pulledOut}</b>Deployed</span><span><b>2</b>Maintenance</span></div><article className="panel data-panel"><div className="table-tools"><div className="search-box"><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search ID, equipment, category, event…"/></div><select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Equipment status"><option value="all">All status</option><option value="available">Available</option><option value="pulled_out">Pulled out</option></select><button className="filter-chip">All Categories</button></div><div className="table-scroll"><table><thead><tr><th>Equipment ID</th><th>Equipment</th><th>Category</th><th>Storage</th><th>Condition</th><th>Status</th><th>Assigned Event</th></tr></thead><tbody>{filtered.map((a,i)=><tr key={a.id}><td><code>{a.assetCode}</code></td><td><div className="equipment-cell"><span className="equip-thumb"><Icon name="box"/></span><div><b>{a.name}</b><small>{["Pro Series","Stageability Asset","Rental Fleet"][i%3]}</small></div></div></td><td>{a.category}</td><td>{["Rack A-01","Lighting Bay","LED Storage","Truss Zone"][i%4]}</td><td><Status value={i===4?"For Check":"Good"}/></td><td><Status value={a.status==="available"?"Available":"Pulled Out"}/></td><td>{a.currentEvent||<span className="muted">—</span>}</td></tr>)}</tbody></table></div></article></>}

function Pullout({inventory,back,eventName,setEventName,operatorName,setOperatorName,scan,submitting}:{inventory:InventoryData;back:BackOfficeData;eventName:string;setEventName:(s:string)=>void;operatorName:string;setOperatorName:(s:string)=>void;scan:(s:"pullout"|"return")=>void;submitting:boolean}) {return <><PageHead kicker="EQUIPMENT ACCOUNTABILITY" title="Pull-Out & Return Control" sub="Scan, release, receive, and audit every asset movement from warehouse to event and back."/><div className="pullout-layout"><article className="panel scan-console"><div className="scan-visual"><Icon name="scan" size={48}/><span>READY TO SCAN</span><small>Code 128 • QR Code • Manual ID</small></div><label>Event Assignment<select value={eventName} onChange={e=>setEventName(e.target.value)}><option value="">Select event / project</option>{back.events.map(e=><option key={e.id} value={e.title}>{e.title} — {e.eventDate}</option>)}</select></label><label>Responsible Staff<select value={operatorName} onChange={e=>setOperatorName(e.target.value)}><option value="">Select warehouse staff / crew</option>{back.staff.map(s=><option key={s.id} value={s.fullName}>{s.fullName} — {s.role}</option>)}</select></label><div className="scan-buttons"><button disabled={submitting||!eventName||!operatorName} className="release" onClick={()=>scan("pullout")}><Icon name="out"/><span><b>SCAN PULL-OUT</b><small>Release equipment</small></span></button><button disabled={submitting||!operatorName} className="receive" onClick={()=>scan("return")}><Icon name="back"/><span><b>SCAN RETURN</b><small>Receive at warehouse</small></span></button></div><div className="signature-status"><span><Icon name="shield"/>Release signature required</span><span><Icon name="shield"/>Return inspection required</span></div></article><article className="panel manifest"><div className="panel-title"><div><span className="kicker">IMMUTABLE AUDIT TRAIL</span><h2>Equipment Movement History</h2></div><span className="locked"><Icon name="shield"/>Protected</span></div><div className="movement-list">{inventory.movements.length?inventory.movements.map(m=><div key={m.id}><span className={`movement-icon ${m.action}`}><Icon name={m.action==="pullout"?"out":"back"}/></span><div><b>{m.assetName}</b><code>{m.assetCode}</code><p>{m.eventName}</p><small>{m.operatorName||"Unassigned staff"} • {new Date(m.createdAt+"Z").toLocaleString("en-PH",{dateStyle:"medium",timeStyle:"short"})}</small></div><Status value={m.action}/></div>):<p className="empty-state">No equipment movement recorded yet.</p>}</div></article></div></>}

function Events({data}:{data:BackOfficeData}) {return <><PageHead kicker="EVENT OPERATIONS" title="Event Calendar & Bookings" sub="Plan schedules, venues, crew assignments, equipment reservations, and event status." actions={<button className="btn primary"><Icon name="plus"/>New Event</button>}/><div className="event-board">{data.events.map(e=><article className="event-card" key={e.id}><div className="event-date"><b>{new Date(e.eventDate+"T00:00:00").getDate()}</b><span>{new Date(e.eventDate+"T00:00:00").toLocaleDateString("en-PH",{month:"short"}).toUpperCase()}</span><small>2026</small></div><div className="event-info"><div><code>{e.eventCode}</code><Status value={e.status}/></div><h3>{e.title}</h3><p>{e.clientName}</p><span><Icon name="warehouse"/> {e.venue}</span><footer><small><Icon name="users"/> {e.crewCount} crew</small><small><Icon name="box"/> {e.equipmentCount} equipment</small></footer></div></article>)}</div><article className="panel calendar-strip"><div className="panel-title"><div><span className="kicker">JULY 2026</span><h2>Booking Schedule</h2></div></div><div className="week-row">{["MON 20","TUE 21","WED 22","THU 23","FRI 24","SAT 25","SUN 26"].map((d,i)=><div key={d} className={i===0||i===3||i===5?"has-event":""}><b>{d.split(" ")[1]}</b><small>{d.split(" ")[0]}</small>{i===0&&<span>WEDDING</span>}{i===3&&<span>CONFERENCE</span>}{i===5&&<span>GRADUATION</span>}</div>)}</div></article></>}

function Clients({data}:{data:BackOfficeData}) {return <><PageHead kicker="CLIENT RELATIONSHIP MANAGEMENT" title="Clients, Quotations & Billing" sub="Central client database with quotations, contracts, invoices, payment history, and balances." actions={<button className="btn primary"><Icon name="plus"/>New Client</button>}/><div className="client-stats"><MetricCard label="ACTIVE CLIENTS" value={data.clients.length} detail="in current database" icon="users"/><MetricCard label="PENDING QUOTATIONS" value={data.quotations.filter(q=>q.status==="pending").length} detail="requires follow-up" icon="report" tone="amber"/><MetricCard label="ACCOUNTS RECEIVABLE" value={peso.format(data.clients.reduce((s,c)=>s+c.balance,0))} detail="outstanding balances" icon="wallet" tone="red"/></div><div className="two-cols"><article className="panel data-panel"><div className="panel-title"><div><span className="kicker">CLIENT DATABASE</span><h2>Client Accounts</h2></div></div><div className="table-scroll"><table><thead><tr><th>Client</th><th>Contact</th><th>Balance</th><th>Status</th></tr></thead><tbody>{data.clients.map(c=><tr key={c.id}><td><div className="person-cell"><Avatar name={c.name}/><div><b>{c.name}</b><small>{c.company||c.clientCode}</small></div></div></td><td><span>{c.contact}</span><small className="block">{c.email}</small></td><td className={c.balance>0?"money-due":""}>{peso.format(c.balance)}</td><td><Status value={c.balance>0?"Outstanding":"Paid"}/></td></tr>)}</tbody></table></div></article><article className="panel quote-panel"><div className="panel-title"><div><span className="kicker">SALES PIPELINE</span><h2>Latest Quotations</h2></div></div>{data.quotations.map(q=><div className="quote-row" key={q.id}><div><code>{q.quoteNo}</code><b>{q.eventName}</b><small>{q.clientName}</small></div><div><strong>{peso.format(q.amount)}</strong><Status value={q.status}/></div></div>)}</article></div></>}

function StaffPage({data}:{data:BackOfficeData}) {const roles=["Super Admin","Admin","Office Staff","Warehouse Staff","Technician","Crew"];return <><PageHead kicker="PEOPLE & ACCOUNTABILITY" title="Staff & User Management" sub="Role-based accounts, attendance, work assignments, and security status." actions={<button className="btn primary"><Icon name="plus"/>Add Staff Account</button>}/><div className="staff-summary"><div><b>{data.metrics.attendancePresent}/{data.metrics.attendanceTotal}</b><span>Present / On-site</span></div>{roles.map(r=><div key={r}><b>{data.staff.filter(s=>s.role===r).length}</b><span>{r}</span></div>)}</div><div className="staff-grid">{data.staff.map(s=><article className="staff-card" key={s.id}><div className="staff-top"><Avatar name={s.fullName}/><div><Status value={s.attendanceStatus}/><span className={`security-dot ${s.twoFactorEnabled?"on":"off"}`} title={s.twoFactorEnabled?"2FA enabled":"2FA pending"}/></div></div><h3>{s.fullName}</h3><p>{s.position}</p><code>{s.employeeId}</code><dl><div><dt>Role</dt><dd>{s.role}</dd></div><div><dt>Username</dt><dd>{s.username}</dd></div><div><dt>Contact</dt><dd>{s.contactNumber}</dd></div><div><dt>Account</dt><dd>{s.accountStatus}</dd></div></dl><footer><span><Icon name="shield"/>{s.twoFactorEnabled?"2FA Enabled":"2FA Pending"}</span><button aria-label={`View ${s.fullName}`}><Icon name="eye"/></button></footer></article>)}</div></>}

function Finance({data}:{data:BackOfficeData}) {const income=data.finance.filter(f=>f.type==="income").reduce((s,f)=>s+f.amount,0), expenses=data.finance.filter(f=>f.type==="expense").reduce((s,f)=>s+f.amount,0);return <><PageHead kicker="FINANCIAL CONTROL" title="Finance & Accounting" sub="Income, expenses, payroll, petty cash, receivables, payables, and profitability." actions={<button className="btn primary"><Icon name="plus"/>New Transaction</button>}/><div className="finance-metrics"><MetricCard label="MONTHLY INCOME" value={peso.format(income)} detail="posted transactions" icon="wallet" tone="green"/><MetricCard label="MONTHLY EXPENSES" value={peso.format(expenses)} detail="operating costs" icon="wallet" tone="red"/><MetricCard label="NET PROFIT" value={peso.format(income-expenses)} detail={`${Math.round((income-expenses)/income*100)}% margin`} icon="report" tone="blue"/><MetricCard label="RECEIVABLES" value={peso.format(data.clients.reduce((s,c)=>s+c.balance,0))} detail="client balances" icon="users" tone="amber"/></div><div className="two-cols finance-cols"><article className="panel"><div className="panel-title"><div><span className="kicker">PROFIT & LOSS</span><h2>Six-Month Performance</h2></div></div><RevenueChart/></article><article className="panel"><div className="panel-title"><div><span className="kicker">EXPENSE MIX</span><h2>Expense Allocation</h2></div></div><div className="expense-bars">{[["Equipment & Maintenance",42],["Payroll",31],["Logistics & Fuel",17],["Office & Other",10]].map(([l,v])=><div key={String(l)}><span>{l}<b>{v}%</b></span><i><em style={{width:`${v}%`}}/></i></div>)}</div></article></div><article className="panel data-panel"><div className="panel-title"><div><span className="kicker">GENERAL LEDGER</span><h2>Recent Transactions</h2></div></div><div className="table-scroll"><table><thead><tr><th>Date</th><th>Type</th><th>Category</th><th>Description</th><th>Event</th><th>Amount</th></tr></thead><tbody>{data.finance.map(f=><tr key={f.id}><td>{f.entryDate}</td><td><Status value={f.type}/></td><td>{f.category}</td><td><b>{f.description}</b></td><td>{f.eventName||"—"}</td><td className={f.type==="income"?"money-in":"money-out"}>{f.type==="income"?"+":"−"}{peso.format(f.amount)}</td></tr>)}</tbody></table></div></article></>}

function Warehouse({data}:{data:BackOfficeData}) {return <><PageHead kicker="WAREHOUSE CONTROL" title="Stock, Consumables & Suppliers" sub="Monitor consumables, purchase orders, receiving, transfers, and stock adjustments." actions={<button className="btn primary"><Icon name="plus"/>Stock Adjustment</button>}/><div className="warehouse-layout"><article className="panel data-panel"><div className="panel-title"><div><span className="kicker">LIVE STOCK</span><h2>Consumables Inventory</h2></div><span className="stock-alert">{data.warehouse.filter(w=>w.stock<=w.minStock).length} low-stock items</span></div><div className="table-scroll"><table><thead><tr><th>Item Code</th><th>Item</th><th>Category</th><th>Stock Level</th><th>Minimum</th><th>Supplier</th><th>Status</th></tr></thead><tbody>{data.warehouse.map(w=>{const low=w.stock<=w.minStock;return <tr key={w.id}><td><code>{w.itemCode}</code></td><td><b>{w.name}</b></td><td>{w.category}</td><td><div className="stock-level"><span>{w.stock} {w.unit}</span><i><em className={low?"low":""} style={{width:`${Math.min(100,w.stock/Math.max(w.minStock*2,1)*100)}%`}}/></i></div></td><td>{w.minStock} {w.unit}</td><td>{w.supplier}</td><td><Status value={low?"Low Stock":"In Stock"}/></td></tr>})}</tbody></table></div></article><aside className="warehouse-side"><article className="panel mini-panel"><span className="kicker">PURCHASING</span><h3>Open Purchase Orders</h3><b className="big-number">3</b><p>Total value: {peso.format(68400)}</p><button className="text-btn">View purchase orders →</button></article><article className="panel mini-panel"><span className="kicker">RECEIVING</span><h3>Expected Deliveries</h3><b className="big-number">2</b><p>Next delivery: Jul 19</p><button className="text-btn">Receiving reports →</button></article><article className="panel mini-panel"><span className="kicker">SUPPLIERS</span><h3>Approved Suppliers</h3><b className="big-number">14</b><p>2 pending accreditation</p><button className="text-btn">Supplier directory →</button></article></aside></div></>}

function Reports({inventory,back,exportCsv}:{inventory:InventoryData;back:BackOfficeData;exportCsv:(n:string,r:Record<string,unknown>[])=>void}) {const reports=[{title:"Equipment Inventory",desc:"All assets, locations, conditions and status",icon:"box",rows:inventory.items},{title:"Pull-Out History",desc:"Release records by event, staff and timestamp",icon:"out",rows:inventory.movements.filter(m=>m.action==="pullout")},{title:"Return History",desc:"Warehouse receiving and inspection records",icon:"back",rows:inventory.movements.filter(m=>m.action==="return")},{title:"Staff Accountability",desc:"Roles, attendance and account status",icon:"badge",rows:back.staff},{title:"Client List",desc:"Client contacts, balances and history",icon:"users",rows:back.clients},{title:"Sales Report",desc:"Revenue transactions and event income",icon:"wallet",rows:back.finance.filter(f=>f.type==="income")},{title:"Expense Report",desc:"Operating costs by category and period",icon:"report",rows:back.finance.filter(f=>f.type==="expense")},{title:"Maintenance History",desc:"Asset repairs, due dates and technicians",icon:"shield",rows:back.maintenance}];const printReport=()=>{document.body.classList.remove("print-labels");window.print()};return <><PageHead kicker="PROFESSIONAL REPORTING" title="Reports & Data Exports" sub="Generate print-ready PDF summaries and Excel-compatible CSV files for management and audit."/><div className="report-grid">{reports.map(r=><article className="report-card" key={r.title}><span><Icon name={r.icon} size={24}/></span><div><h3>{r.title}</h3><p>{r.desc}</p><small>{r.rows.length} records available</small></div><footer><button onClick={printReport}><Icon name="print"/>PDF / Print</button><button onClick={()=>exportCsv(r.title.toLowerCase().replaceAll(" ","-"),r.rows as unknown as Record<string,unknown>[])}><Icon name="download"/>Excel CSV</button></footer></article>)}</div></>}

function Notifications({data}:{data:BackOfficeData}) {return <><PageHead kicker="ALERT CENTER" title="Notifications & Reminders" sub="Low stock, maintenance, events, quotations, balances, and overdue returns." actions={<button className="btn secondary">Mark all as read</button>}/><div className="notification-layout"><article className="panel notification-list">{data.notifications.map(n=><div key={n.id} className={`notification ${n.severity}`}><span><Icon name={n.type==="event"?"calendar":n.type==="balance"?"wallet":"bell"}/></span><div><div><b>{n.title}</b><Status value={n.severity}/></div><p>{n.message}</p><small>Due {n.dueDate}</small></div><button aria-label="Mark notification read">•••</button></div>)}</article><aside className="panel notification-filter"><span className="kicker">FILTERS</span>{["All notifications","Low stock","Maintenance","Upcoming events","Quotations","Outstanding balances","Overdue returns"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}<span>{i===0?data.notifications.length:i<5?1:0}</span></button>)}</aside></div></>}

function Security({data}:{data:BackOfficeData}) {const roles=[{r:"Super Admin",a:"Full system access"},{r:"Admin",a:"Operations and approvals"},{r:"Office Staff",a:"Clients, finance and reports"},{r:"Warehouse Staff",a:"Inventory, release and receiving"},{r:"Technician",a:"Maintenance and equipment history"},{r:"Crew",a:"Assigned events and accountability"}];return <><PageHead kicker="SECURITY & GOVERNANCE" title="Security Center" sub="Role permissions, access protection, activity logging, backups, and account security."/><div className="security-cards"><article><span className="secure"><Icon name="shield"/></span><div><small>ROLE-BASED ACCESS</small><b>Configured</b><p>6 operational roles defined</p></div></article><article><span className="warning"><Icon name="shield"/></span><div><small>TWO-FACTOR AUTH</small><b>{data.staff.filter(s=>s.twoFactorEnabled).length}/{data.staff.length} enrolled</b><p>Complete staff enrollment</p></div></article><article><span className="secure"><Icon name="report"/></span><div><small>ACTIVITY LOGS</small><b>Protected</b><p>Audit trail append-only</p></div></article><article><span className="secure"><Icon name="cloud"/></span><div><small>CLOUD DATABASE</small><b>Connected</b><p>Encrypted transport</p></div></article></div><div className="two-cols security-cols"><article className="panel"><div className="panel-title"><div><span className="kicker">ROLE MATRIX</span><h2>Permissions Overview</h2></div></div><div className="role-matrix">{roles.map(x=><div key={x.r}><span><Icon name="shield"/></span><div><b>{x.r}</b><p>{x.a}</p></div><Status value="Active"/></div>)}</div></article><article className="panel security-audit"><div className="panel-title"><div><span className="kicker">SECURITY STATUS</span><h2>Protection Checklist</h2></div></div>{[["Password policy","Enforced","good"],["Two-factor authentication","Partial enrollment","warn"],["Automatic backups","Platform managed","good"],["Database encryption","At rest & in transit","good"],["IP login monitoring","Requires login service","warn"],["Last security review","July 17, 2026","good"]].map(x=><div key={x[0]}><span className={x[2]}/><b>{x[0]}</b><small>{x[1]}</small></div>)}</article></div><div className="security-note"><Icon name="shield"/><div><b>Production security note</b><p>The management workspace is now visually and structurally prepared for role-based operations. Before storing confidential payroll, contracts, passwords, or official receipts, connect a dedicated identity provider and complete 2FA enrollment for every staff account.</p></div></div></>}
